# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Desktop/framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Desktop/framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Desktop/framework/CMakeFiles /root/Desktop/framework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Desktop/framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Framework

# Build rule for target.
Framework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Framework
.PHONY : Framework

# fast build rule for target.
Framework/fast:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/build
.PHONY : Framework/fast

core/src/Application.o: core/src/Application.cpp.o

.PHONY : core/src/Application.o

# target to build an object file
core/src/Application.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Application.cpp.o
.PHONY : core/src/Application.cpp.o

core/src/Application.i: core/src/Application.cpp.i

.PHONY : core/src/Application.i

# target to preprocess a source file
core/src/Application.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Application.cpp.i
.PHONY : core/src/Application.cpp.i

core/src/Application.s: core/src/Application.cpp.s

.PHONY : core/src/Application.s

# target to generate assembly for a file
core/src/Application.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Application.cpp.s
.PHONY : core/src/Application.cpp.s

core/src/Exception.o: core/src/Exception.cpp.o

.PHONY : core/src/Exception.o

# target to build an object file
core/src/Exception.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Exception.cpp.o
.PHONY : core/src/Exception.cpp.o

core/src/Exception.i: core/src/Exception.cpp.i

.PHONY : core/src/Exception.i

# target to preprocess a source file
core/src/Exception.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Exception.cpp.i
.PHONY : core/src/Exception.cpp.i

core/src/Exception.s: core/src/Exception.cpp.s

.PHONY : core/src/Exception.s

# target to generate assembly for a file
core/src/Exception.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Exception.cpp.s
.PHONY : core/src/Exception.cpp.s

core/src/Notifier.o: core/src/Notifier.cpp.o

.PHONY : core/src/Notifier.o

# target to build an object file
core/src/Notifier.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Notifier.cpp.o
.PHONY : core/src/Notifier.cpp.o

core/src/Notifier.i: core/src/Notifier.cpp.i

.PHONY : core/src/Notifier.i

# target to preprocess a source file
core/src/Notifier.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Notifier.cpp.i
.PHONY : core/src/Notifier.cpp.i

core/src/Notifier.s: core/src/Notifier.cpp.s

.PHONY : core/src/Notifier.s

# target to generate assembly for a file
core/src/Notifier.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Notifier.cpp.s
.PHONY : core/src/Notifier.cpp.s

core/src/NotifyManager.o: core/src/NotifyManager.cpp.o

.PHONY : core/src/NotifyManager.o

# target to build an object file
core/src/NotifyManager.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/NotifyManager.cpp.o
.PHONY : core/src/NotifyManager.cpp.o

core/src/NotifyManager.i: core/src/NotifyManager.cpp.i

.PHONY : core/src/NotifyManager.i

# target to preprocess a source file
core/src/NotifyManager.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/NotifyManager.cpp.i
.PHONY : core/src/NotifyManager.cpp.i

core/src/NotifyManager.s: core/src/NotifyManager.cpp.s

.PHONY : core/src/NotifyManager.s

# target to generate assembly for a file
core/src/NotifyManager.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/NotifyManager.cpp.s
.PHONY : core/src/NotifyManager.cpp.s

core/src/SharedLibraryLoader.o: core/src/SharedLibraryLoader.cpp.o

.PHONY : core/src/SharedLibraryLoader.o

# target to build an object file
core/src/SharedLibraryLoader.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/SharedLibraryLoader.cpp.o
.PHONY : core/src/SharedLibraryLoader.cpp.o

core/src/SharedLibraryLoader.i: core/src/SharedLibraryLoader.cpp.i

.PHONY : core/src/SharedLibraryLoader.i

# target to preprocess a source file
core/src/SharedLibraryLoader.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/SharedLibraryLoader.cpp.i
.PHONY : core/src/SharedLibraryLoader.cpp.i

core/src/SharedLibraryLoader.s: core/src/SharedLibraryLoader.cpp.s

.PHONY : core/src/SharedLibraryLoader.s

# target to generate assembly for a file
core/src/SharedLibraryLoader.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/SharedLibraryLoader.cpp.s
.PHONY : core/src/SharedLibraryLoader.cpp.s

core/src/SharedLibraryManager.o: core/src/SharedLibraryManager.cpp.o

.PHONY : core/src/SharedLibraryManager.o

# target to build an object file
core/src/SharedLibraryManager.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/SharedLibraryManager.cpp.o
.PHONY : core/src/SharedLibraryManager.cpp.o

core/src/SharedLibraryManager.i: core/src/SharedLibraryManager.cpp.i

.PHONY : core/src/SharedLibraryManager.i

# target to preprocess a source file
core/src/SharedLibraryManager.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/SharedLibraryManager.cpp.i
.PHONY : core/src/SharedLibraryManager.cpp.i

core/src/SharedLibraryManager.s: core/src/SharedLibraryManager.cpp.s

.PHONY : core/src/SharedLibraryManager.s

# target to generate assembly for a file
core/src/SharedLibraryManager.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/SharedLibraryManager.cpp.s
.PHONY : core/src/SharedLibraryManager.cpp.s

core/src/Thread.o: core/src/Thread.cpp.o

.PHONY : core/src/Thread.o

# target to build an object file
core/src/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Thread.cpp.o
.PHONY : core/src/Thread.cpp.o

core/src/Thread.i: core/src/Thread.cpp.i

.PHONY : core/src/Thread.i

# target to preprocess a source file
core/src/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Thread.cpp.i
.PHONY : core/src/Thread.cpp.i

core/src/Thread.s: core/src/Thread.cpp.s

.PHONY : core/src/Thread.s

# target to generate assembly for a file
core/src/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/Thread.cpp.s
.PHONY : core/src/Thread.cpp.s

core/src/ThreadPool.o: core/src/ThreadPool.cpp.o

.PHONY : core/src/ThreadPool.o

# target to build an object file
core/src/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/ThreadPool.cpp.o
.PHONY : core/src/ThreadPool.cpp.o

core/src/ThreadPool.i: core/src/ThreadPool.cpp.i

.PHONY : core/src/ThreadPool.i

# target to preprocess a source file
core/src/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/ThreadPool.cpp.i
.PHONY : core/src/ThreadPool.cpp.i

core/src/ThreadPool.s: core/src/ThreadPool.cpp.s

.PHONY : core/src/ThreadPool.s

# target to generate assembly for a file
core/src/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/core/src/ThreadPool.cpp.s
.PHONY : core/src/ThreadPool.cpp.s

ipc/src/SharedMemory.o: ipc/src/SharedMemory.cpp.o

.PHONY : ipc/src/SharedMemory.o

# target to build an object file
ipc/src/SharedMemory.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/ipc/src/SharedMemory.cpp.o
.PHONY : ipc/src/SharedMemory.cpp.o

ipc/src/SharedMemory.i: ipc/src/SharedMemory.cpp.i

.PHONY : ipc/src/SharedMemory.i

# target to preprocess a source file
ipc/src/SharedMemory.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/ipc/src/SharedMemory.cpp.i
.PHONY : ipc/src/SharedMemory.cpp.i

ipc/src/SharedMemory.s: ipc/src/SharedMemory.cpp.s

.PHONY : ipc/src/SharedMemory.s

# target to generate assembly for a file
ipc/src/SharedMemory.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/ipc/src/SharedMemory.cpp.s
.PHONY : ipc/src/SharedMemory.cpp.s

ipc/src/Transceiver.o: ipc/src/Transceiver.cpp.o

.PHONY : ipc/src/Transceiver.o

# target to build an object file
ipc/src/Transceiver.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/ipc/src/Transceiver.cpp.o
.PHONY : ipc/src/Transceiver.cpp.o

ipc/src/Transceiver.i: ipc/src/Transceiver.cpp.i

.PHONY : ipc/src/Transceiver.i

# target to preprocess a source file
ipc/src/Transceiver.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/ipc/src/Transceiver.cpp.i
.PHONY : ipc/src/Transceiver.cpp.i

ipc/src/Transceiver.s: ipc/src/Transceiver.cpp.s

.PHONY : ipc/src/Transceiver.s

# target to generate assembly for a file
ipc/src/Transceiver.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/ipc/src/Transceiver.cpp.s
.PHONY : ipc/src/Transceiver.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/main.cpp.s
.PHONY : main.cpp.s

util/src/File.o: util/src/File.cpp.o

.PHONY : util/src/File.o

# target to build an object file
util/src/File.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/File.cpp.o
.PHONY : util/src/File.cpp.o

util/src/File.i: util/src/File.cpp.i

.PHONY : util/src/File.i

# target to preprocess a source file
util/src/File.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/File.cpp.i
.PHONY : util/src/File.cpp.i

util/src/File.s: util/src/File.cpp.s

.PHONY : util/src/File.s

# target to generate assembly for a file
util/src/File.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/File.cpp.s
.PHONY : util/src/File.cpp.s

util/src/Logger.o: util/src/Logger.cpp.o

.PHONY : util/src/Logger.o

# target to build an object file
util/src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Logger.cpp.o
.PHONY : util/src/Logger.cpp.o

util/src/Logger.i: util/src/Logger.cpp.i

.PHONY : util/src/Logger.i

# target to preprocess a source file
util/src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Logger.cpp.i
.PHONY : util/src/Logger.cpp.i

util/src/Logger.s: util/src/Logger.cpp.s

.PHONY : util/src/Logger.s

# target to generate assembly for a file
util/src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Logger.cpp.s
.PHONY : util/src/Logger.cpp.s

util/src/Option.o: util/src/Option.cpp.o

.PHONY : util/src/Option.o

# target to build an object file
util/src/Option.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Option.cpp.o
.PHONY : util/src/Option.cpp.o

util/src/Option.i: util/src/Option.cpp.i

.PHONY : util/src/Option.i

# target to preprocess a source file
util/src/Option.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Option.cpp.i
.PHONY : util/src/Option.cpp.i

util/src/Option.s: util/src/Option.cpp.s

.PHONY : util/src/Option.s

# target to generate assembly for a file
util/src/Option.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Option.cpp.s
.PHONY : util/src/Option.cpp.s

util/src/Runnable.o: util/src/Runnable.cpp.o

.PHONY : util/src/Runnable.o

# target to build an object file
util/src/Runnable.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Runnable.cpp.o
.PHONY : util/src/Runnable.cpp.o

util/src/Runnable.i: util/src/Runnable.cpp.i

.PHONY : util/src/Runnable.i

# target to preprocess a source file
util/src/Runnable.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Runnable.cpp.i
.PHONY : util/src/Runnable.cpp.i

util/src/Runnable.s: util/src/Runnable.cpp.s

.PHONY : util/src/Runnable.s

# target to generate assembly for a file
util/src/Runnable.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/Runnable.cpp.s
.PHONY : util/src/Runnable.cpp.s

util/src/TimerManager.o: util/src/TimerManager.cpp.o

.PHONY : util/src/TimerManager.o

# target to build an object file
util/src/TimerManager.cpp.o:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/TimerManager.cpp.o
.PHONY : util/src/TimerManager.cpp.o

util/src/TimerManager.i: util/src/TimerManager.cpp.i

.PHONY : util/src/TimerManager.i

# target to preprocess a source file
util/src/TimerManager.cpp.i:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/TimerManager.cpp.i
.PHONY : util/src/TimerManager.cpp.i

util/src/TimerManager.s: util/src/TimerManager.cpp.s

.PHONY : util/src/TimerManager.s

# target to generate assembly for a file
util/src/TimerManager.cpp.s:
	$(MAKE) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util/src/TimerManager.cpp.s
.PHONY : util/src/TimerManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Framework"
	@echo "... core/src/Application.o"
	@echo "... core/src/Application.i"
	@echo "... core/src/Application.s"
	@echo "... core/src/Exception.o"
	@echo "... core/src/Exception.i"
	@echo "... core/src/Exception.s"
	@echo "... core/src/Notifier.o"
	@echo "... core/src/Notifier.i"
	@echo "... core/src/Notifier.s"
	@echo "... core/src/NotifyManager.o"
	@echo "... core/src/NotifyManager.i"
	@echo "... core/src/NotifyManager.s"
	@echo "... core/src/SharedLibraryLoader.o"
	@echo "... core/src/SharedLibraryLoader.i"
	@echo "... core/src/SharedLibraryLoader.s"
	@echo "... core/src/SharedLibraryManager.o"
	@echo "... core/src/SharedLibraryManager.i"
	@echo "... core/src/SharedLibraryManager.s"
	@echo "... core/src/Thread.o"
	@echo "... core/src/Thread.i"
	@echo "... core/src/Thread.s"
	@echo "... core/src/ThreadPool.o"
	@echo "... core/src/ThreadPool.i"
	@echo "... core/src/ThreadPool.s"
	@echo "... ipc/src/SharedMemory.o"
	@echo "... ipc/src/SharedMemory.i"
	@echo "... ipc/src/SharedMemory.s"
	@echo "... ipc/src/Transceiver.o"
	@echo "... ipc/src/Transceiver.i"
	@echo "... ipc/src/Transceiver.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... util/src/File.o"
	@echo "... util/src/File.i"
	@echo "... util/src/File.s"
	@echo "... util/src/Logger.o"
	@echo "... util/src/Logger.i"
	@echo "... util/src/Logger.s"
	@echo "... util/src/Option.o"
	@echo "... util/src/Option.i"
	@echo "... util/src/Option.s"
	@echo "... util/src/Runnable.o"
	@echo "... util/src/Runnable.i"
	@echo "... util/src/Runnable.s"
	@echo "... util/src/TimerManager.o"
	@echo "... util/src/TimerManager.i"
	@echo "... util/src/TimerManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

